flight = input('Введите номер рейса: ')
name = input('Введите название авиакомпании на русском языке: ')
name1 = input('Введите название авиакомпании на английском языке: ')
city = input('Введите город прилета на русском языке: ')
city1 = input('Введите город прилете на английском языке: ')
print('Заканчиавается посадка на рейс '+ flight + ' авиакомпании '+ name + ' до города '+ city )
print('This is the final boarding call for ' +name1 + ' flight '+ flight +  ' to  ' + city1)